language: python
cache: bundler
python:
   - 3.6
install:
   # Install the latest release of Vale:
   - curl -sL https://install.goreleaser.com/github.com/ValeLint/vale.sh | bash
   - export PATH=./bin:"$PATH"

   - bundle install --jobs=3

   - pip install yamllint
   - pip install markdata
   - pip install pyyaml

   # Deps
   - pip install docutils
before_script:
   - yamllint -c '.yamllint.yml' RuleBase
script:
   - cucumber
   - zip -r LegalRules.zip RuleBase -x "*.DS_Store"
deploy:
   provider: releases
   api_key: $GITHUB_TOKEN
   file: LegalRules.zip
   skip_cleanup: true
   on:
      tags: true